// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListUserOKCode is the HTTP code returned for type ListUserOK
const ListUserOKCode int = 200

/*ListUserOK OK

swagger:response listUserOK
*/
type ListUserOK struct {

	/*
	  In: Body
	*/
	Payload []*ListUserOKBodyItems0 `json:"body,omitempty"`
}

// NewListUserOK creates ListUserOK with default headers values
func NewListUserOK() *ListUserOK {

	return &ListUserOK{}
}

// WithPayload adds the payload to the list user o k response
func (o *ListUserOK) WithPayload(payload []*ListUserOKBodyItems0) *ListUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user o k response
func (o *ListUserOK) SetPayload(payload []*ListUserOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*ListUserOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListUserUnauthorizedCode is the HTTP code returned for type ListUserUnauthorized
const ListUserUnauthorizedCode int = 401

/*ListUserUnauthorized Unauthorized

swagger:response listUserUnauthorized
*/
type ListUserUnauthorized struct {
}

// NewListUserUnauthorized creates ListUserUnauthorized with default headers values
func NewListUserUnauthorized() *ListUserUnauthorized {

	return &ListUserUnauthorized{}
}

// WriteResponse to the client
func (o *ListUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// ListUserForbiddenCode is the HTTP code returned for type ListUserForbidden
const ListUserForbiddenCode int = 403

/*ListUserForbidden Forbidden

swagger:response listUserForbidden
*/
type ListUserForbidden struct {
}

// NewListUserForbidden creates ListUserForbidden with default headers values
func NewListUserForbidden() *ListUserForbidden {

	return &ListUserForbidden{}
}

// WriteResponse to the client
func (o *ListUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
