// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ModifyUserOKCode is the HTTP code returned for type ModifyUserOK
const ModifyUserOKCode int = 200

/*ModifyUserOK update success

swagger:response modifyUserOK
*/
type ModifyUserOK struct {

	/*
	  In: Body
	*/
	Payload *ModifyUserOKBody `json:"body,omitempty"`
}

// NewModifyUserOK creates ModifyUserOK with default headers values
func NewModifyUserOK() *ModifyUserOK {

	return &ModifyUserOK{}
}

// WithPayload adds the payload to the modify user o k response
func (o *ModifyUserOK) WithPayload(payload *ModifyUserOKBody) *ModifyUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the modify user o k response
func (o *ModifyUserOK) SetPayload(payload *ModifyUserOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ModifyUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ModifyUserUnauthorizedCode is the HTTP code returned for type ModifyUserUnauthorized
const ModifyUserUnauthorizedCode int = 401

/*ModifyUserUnauthorized Unauthorized

swagger:response modifyUserUnauthorized
*/
type ModifyUserUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *ModifyUserUnauthorizedBody `json:"body,omitempty"`
}

// NewModifyUserUnauthorized creates ModifyUserUnauthorized with default headers values
func NewModifyUserUnauthorized() *ModifyUserUnauthorized {

	return &ModifyUserUnauthorized{}
}

// WithPayload adds the payload to the modify user unauthorized response
func (o *ModifyUserUnauthorized) WithPayload(payload *ModifyUserUnauthorizedBody) *ModifyUserUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the modify user unauthorized response
func (o *ModifyUserUnauthorized) SetPayload(payload *ModifyUserUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ModifyUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ModifyUserForbiddenCode is the HTTP code returned for type ModifyUserForbidden
const ModifyUserForbiddenCode int = 403

/*ModifyUserForbidden Forbidden

swagger:response modifyUserForbidden
*/
type ModifyUserForbidden struct {

	/*
	  In: Body
	*/
	Payload *ModifyUserForbiddenBody `json:"body,omitempty"`
}

// NewModifyUserForbidden creates ModifyUserForbidden with default headers values
func NewModifyUserForbidden() *ModifyUserForbidden {

	return &ModifyUserForbidden{}
}

// WithPayload adds the payload to the modify user forbidden response
func (o *ModifyUserForbidden) WithPayload(payload *ModifyUserForbiddenBody) *ModifyUserForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the modify user forbidden response
func (o *ModifyUserForbidden) SetPayload(payload *ModifyUserForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ModifyUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ModifyUserNotFoundCode is the HTTP code returned for type ModifyUserNotFound
const ModifyUserNotFoundCode int = 404

/*ModifyUserNotFound resource not found

swagger:response modifyUserNotFound
*/
type ModifyUserNotFound struct {

	/*
	  In: Body
	*/
	Payload *ModifyUserNotFoundBody `json:"body,omitempty"`
}

// NewModifyUserNotFound creates ModifyUserNotFound with default headers values
func NewModifyUserNotFound() *ModifyUserNotFound {

	return &ModifyUserNotFound{}
}

// WithPayload adds the payload to the modify user not found response
func (o *ModifyUserNotFound) WithPayload(payload *ModifyUserNotFoundBody) *ModifyUserNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the modify user not found response
func (o *ModifyUserNotFound) SetPayload(payload *ModifyUserNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ModifyUserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
